-- 1. Tabel Session (Agar login tidak hilang saat di-reload di Vercel)
CREATE TABLE IF NOT EXISTS "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX "IDX_session_expire" ON "session" ("expire");

-- 2. Tabel Experiences (Untuk menyimpan Work & Education)
CREATE TABLE IF NOT EXISTS public.experiences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  subtitle text,
  description text,
  type text NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mengatur RLS (Row Level Security) agar aman dan public read
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Experiences editable by authenticated users only" ON public.experiences FOR ALL USING (auth.role() = 'authenticated');
